FROM ubuntu:20.04 as dashboard-base
RUN apt update && apt install -y git curl
RUN curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh && \
    bash ./nodesource_setup.sh && \
    apt install nodejs && \
    rm ./nodesource_setup.sh

RUN npm install -g @vue/cli@latest

FROM dashboard-base as dashboard-build
ARG BRANCH=master
RUN mkdir -p /usr/local/src && \
    cd /usr/local/src && \
    git clone --depth 1 --branch ${BRANCH} https://github.com/vircadia/metaverse-dashboard.git

RUN cd /usr/local/src/metaverse-dashboard && \
    npm install && npm run build

FROM dashboard-base
ENV USER=cadia
ENV METAVERSEDASHBOARD=metaverse-dashboard

# Add a user for the server to run under
RUN adduser --disabled-password --gecos 'metaverse-server user' ${USER}

WORKDIR /home/${USER}
USER ${USER}:${USER}
RUN mkdir -p /home/${USER}/${METAVERSEDASHBOARD}/dist
RUN mkdir -p /home/${USER}/${METAVERSEDASHBOARD}/log
COPY --from=dashboard-build --chown=${USER}:${USER} /usr/local/src/${METAVERSEDASHBOARD}/package*.json /home/${USER}/${METAVERSEDASHBOARD}/
COPY --from=dashboard-build --chown=${USER}:${USER} /usr/local/src/${METAVERSEDASHBOARD}/dist /home/${USER}/${METAVERSEDASHBOARD}/dist
COPY --chown=${USER}:${USER} ./files/run-metaverse-dashboard.sh /home/${USER}/

# ENTRYPOINT [ "/home/cadia/run-metaverse-dashboard.sh" ]
CMD ["/bin/bash"]